# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '19- FireBase' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Firebase/Core'
  pod 'Firebase/Database'

  # Pods for 19- FireBase

end
